name: Test

on:
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Create SSH Key File For Tests
        run: |
          echo "${{secrets.GOOD_SSH_KEY}}" >>  ~/good.ssh
          echo "${{secrets.BAD_SSH_KEY}}" >> ~/bad.ssh
          chmod 600 ~/good.ssh ~/bad.ssh

      - name: Test
        working-directory: tests/
        run: go test

